#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'AttestationResponse'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 9

# The Active Message type associated with this message.
AM_TYPE = 55

class AttestationResponse(tinyos.message.Message.Message):
    # Create a new AttestationResponse of size 9.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=9):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <AttestationResponse> \n"
        try:
            s += "  [who=0x%x]\n" % (self.get_who())
        except:
            pass
        try:
            s += "  [nonce=0x%x]\n" % (self.get_nonce())
        except:
            pass
        try:
            s += "  [checksum=0x%x]\n" % (self.get_checksum())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: who
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'who' is signed (False).
    #
    def isSigned_who(self):
        return False
    
    #
    # Return whether the field 'who' is an array (False).
    #
    def isArray_who(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'who'
    #
    def offset_who(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'who'
    #
    def offsetBits_who(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'who'
    #
    def get_who(self):
        return self.getUIntElement(self.offsetBits_who(), 8, 1)
    
    #
    # Set the value of the field 'who'
    #
    def set_who(self, value):
        self.setUIntElement(self.offsetBits_who(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'who'
    #
    def size_who(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'who'
    #
    def sizeBits_who(self):
        return 8
    
    #
    # Accessor methods for field: nonce
    #   Field type: long
    #   Offset (bits): 8
    #   Size (bits): 32
    #

    #
    # Return whether the field 'nonce' is signed (False).
    #
    def isSigned_nonce(self):
        return False
    
    #
    # Return whether the field 'nonce' is an array (False).
    #
    def isArray_nonce(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'nonce'
    #
    def offset_nonce(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'nonce'
    #
    def offsetBits_nonce(self):
        return 8
    
    #
    # Return the value (as a long) of the field 'nonce'
    #
    def get_nonce(self):
        return self.getUIntElement(self.offsetBits_nonce(), 32, 1)
    
    #
    # Set the value of the field 'nonce'
    #
    def set_nonce(self, value):
        self.setUIntElement(self.offsetBits_nonce(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'nonce'
    #
    def size_nonce(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'nonce'
    #
    def sizeBits_nonce(self):
        return 32
    
    #
    # Accessor methods for field: checksum
    #   Field type: long
    #   Offset (bits): 40
    #   Size (bits): 32
    #

    #
    # Return whether the field 'checksum' is signed (False).
    #
    def isSigned_checksum(self):
        return False
    
    #
    # Return whether the field 'checksum' is an array (False).
    #
    def isArray_checksum(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'checksum'
    #
    def offset_checksum(self):
        return (40 / 8)
    
    #
    # Return the offset (in bits) of the field 'checksum'
    #
    def offsetBits_checksum(self):
        return 40
    
    #
    # Return the value (as a long) of the field 'checksum'
    #
    def get_checksum(self):
        return self.getUIntElement(self.offsetBits_checksum(), 32, 1)
    
    #
    # Set the value of the field 'checksum'
    #
    def set_checksum(self, value):
        self.setUIntElement(self.offsetBits_checksum(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'checksum'
    #
    def size_checksum(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'checksum'
    #
    def sizeBits_checksum(self):
        return 32
    
