#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DataReading'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 10

# The Active Message type associated with this message.
AM_TYPE = 52

class DataReading(tinyos.message.Message.Message):
    # Create a new DataReading of size 10.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=10):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DataReading> \n"
        try:
            s += "  [testVal=0x%x]\n" % (self.get_testVal())
        except:
            pass
        try:
            s += "  [who=0x%x]\n" % (self.get_who())
        except:
            pass
        try:
            s += "  [temperature=0x%x]\n" % (self.get_temperature())
        except:
            pass
        try:
            s += "  [humidity=0x%x]\n" % (self.get_humidity())
        except:
            pass
        try:
            s += "  [fullSpectrum=0x%x]\n" % (self.get_fullSpectrum())
        except:
            pass
        try:
            s += "  [photoSpectrum=0x%x]\n" % (self.get_photoSpectrum())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: testVal
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'testVal' is signed (False).
    #
    def isSigned_testVal(self):
        return False
    
    #
    # Return whether the field 'testVal' is an array (False).
    #
    def isArray_testVal(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'testVal'
    #
    def offset_testVal(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'testVal'
    #
    def offsetBits_testVal(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'testVal'
    #
    def get_testVal(self):
        return self.getUIntElement(self.offsetBits_testVal(), 8, 1)
    
    #
    # Set the value of the field 'testVal'
    #
    def set_testVal(self, value):
        self.setUIntElement(self.offsetBits_testVal(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'testVal'
    #
    def size_testVal(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'testVal'
    #
    def sizeBits_testVal(self):
        return 8
    
    #
    # Accessor methods for field: who
    #   Field type: short
    #   Offset (bits): 8
    #   Size (bits): 8
    #

    #
    # Return whether the field 'who' is signed (False).
    #
    def isSigned_who(self):
        return False
    
    #
    # Return whether the field 'who' is an array (False).
    #
    def isArray_who(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'who'
    #
    def offset_who(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'who'
    #
    def offsetBits_who(self):
        return 8
    
    #
    # Return the value (as a short) of the field 'who'
    #
    def get_who(self):
        return self.getUIntElement(self.offsetBits_who(), 8, 1)
    
    #
    # Set the value of the field 'who'
    #
    def set_who(self, value):
        self.setUIntElement(self.offsetBits_who(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'who'
    #
    def size_who(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'who'
    #
    def sizeBits_who(self):
        return 8
    
    #
    # Accessor methods for field: temperature
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'temperature' is signed (False).
    #
    def isSigned_temperature(self):
        return False
    
    #
    # Return whether the field 'temperature' is an array (False).
    #
    def isArray_temperature(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'temperature'
    #
    def offset_temperature(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'temperature'
    #
    def offsetBits_temperature(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'temperature'
    #
    def get_temperature(self):
        return self.getUIntElement(self.offsetBits_temperature(), 16, 1)
    
    #
    # Set the value of the field 'temperature'
    #
    def set_temperature(self, value):
        self.setUIntElement(self.offsetBits_temperature(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'temperature'
    #
    def size_temperature(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'temperature'
    #
    def sizeBits_temperature(self):
        return 16
    
    #
    # Accessor methods for field: humidity
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'humidity' is signed (False).
    #
    def isSigned_humidity(self):
        return False
    
    #
    # Return whether the field 'humidity' is an array (False).
    #
    def isArray_humidity(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'humidity'
    #
    def offset_humidity(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'humidity'
    #
    def offsetBits_humidity(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'humidity'
    #
    def get_humidity(self):
        return self.getUIntElement(self.offsetBits_humidity(), 16, 1)
    
    #
    # Set the value of the field 'humidity'
    #
    def set_humidity(self, value):
        self.setUIntElement(self.offsetBits_humidity(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'humidity'
    #
    def size_humidity(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'humidity'
    #
    def sizeBits_humidity(self):
        return 16
    
    #
    # Accessor methods for field: fullSpectrum
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'fullSpectrum' is signed (False).
    #
    def isSigned_fullSpectrum(self):
        return False
    
    #
    # Return whether the field 'fullSpectrum' is an array (False).
    #
    def isArray_fullSpectrum(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'fullSpectrum'
    #
    def offset_fullSpectrum(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'fullSpectrum'
    #
    def offsetBits_fullSpectrum(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'fullSpectrum'
    #
    def get_fullSpectrum(self):
        return self.getUIntElement(self.offsetBits_fullSpectrum(), 16, 1)
    
    #
    # Set the value of the field 'fullSpectrum'
    #
    def set_fullSpectrum(self, value):
        self.setUIntElement(self.offsetBits_fullSpectrum(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'fullSpectrum'
    #
    def size_fullSpectrum(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'fullSpectrum'
    #
    def sizeBits_fullSpectrum(self):
        return 16
    
    #
    # Accessor methods for field: photoSpectrum
    #   Field type: int
    #   Offset (bits): 64
    #   Size (bits): 16
    #

    #
    # Return whether the field 'photoSpectrum' is signed (False).
    #
    def isSigned_photoSpectrum(self):
        return False
    
    #
    # Return whether the field 'photoSpectrum' is an array (False).
    #
    def isArray_photoSpectrum(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'photoSpectrum'
    #
    def offset_photoSpectrum(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'photoSpectrum'
    #
    def offsetBits_photoSpectrum(self):
        return 64
    
    #
    # Return the value (as a int) of the field 'photoSpectrum'
    #
    def get_photoSpectrum(self):
        return self.getUIntElement(self.offsetBits_photoSpectrum(), 16, 1)
    
    #
    # Set the value of the field 'photoSpectrum'
    #
    def set_photoSpectrum(self, value):
        self.setUIntElement(self.offsetBits_photoSpectrum(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'photoSpectrum'
    #
    def size_photoSpectrum(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'photoSpectrum'
    #
    def sizeBits_photoSpectrum(self):
        return 16
    
