#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DataSettings'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 3

# The Active Message type associated with this message.
AM_TYPE = 54

class DataSettings(tinyos.message.Message.Message):
    # Create a new DataSettings of size 3.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=3):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DataSettings> \n"
        try:
            s += "  [testVal=0x%x]\n" % (self.get_testVal())
        except:
            pass
        try:
            s += "  [sampleInterval=0x%x]\n" % (self.get_sampleInterval())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: testVal
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'testVal' is signed (False).
    #
    def isSigned_testVal(self):
        return False
    
    #
    # Return whether the field 'testVal' is an array (False).
    #
    def isArray_testVal(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'testVal'
    #
    def offset_testVal(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'testVal'
    #
    def offsetBits_testVal(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'testVal'
    #
    def get_testVal(self):
        return self.getUIntElement(self.offsetBits_testVal(), 8, 1)
    
    #
    # Set the value of the field 'testVal'
    #
    def set_testVal(self, value):
        self.setUIntElement(self.offsetBits_testVal(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'testVal'
    #
    def size_testVal(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'testVal'
    #
    def sizeBits_testVal(self):
        return 8
    
    #
    # Accessor methods for field: sampleInterval
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sampleInterval' is signed (False).
    #
    def isSigned_sampleInterval(self):
        return False
    
    #
    # Return whether the field 'sampleInterval' is an array (False).
    #
    def isArray_sampleInterval(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sampleInterval'
    #
    def offset_sampleInterval(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'sampleInterval'
    #
    def offsetBits_sampleInterval(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'sampleInterval'
    #
    def get_sampleInterval(self):
        return self.getUIntElement(self.offsetBits_sampleInterval(), 16, 1)
    
    #
    # Set the value of the field 'sampleInterval'
    #
    def set_sampleInterval(self, value):
        self.setUIntElement(self.offsetBits_sampleInterval(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sampleInterval'
    #
    def size_sampleInterval(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sampleInterval'
    #
    def sizeBits_sampleInterval(self):
        return 16
    
